version: '3.1'

services:

  tracker:
    image: humanmade/accelerate-tracker:latest
    ports:
      - 3399:3000
    environment:
      PINPOINT_ENDPOINT: http://pinpoint:3000
      ACCESS_KEY: admin
      SECRET_KEY: password
      CLICKHOUSE_HOST: clickhouse
      DO_CLICKHOUSE: true

  pinpoint:
    image: 'humanmade/local-pinpoint:1.3.0'
    ports:
      - 3333:3000
    environment:
      INDEX_ROTATION: OneDay

  clickhouse:
    image: clickhouse/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - '9020:9000'
      - '8123:8123'
    volumes:
      - ch:/var/lib/clickhouse
      - ./.setup:/.setup

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - '3600:3000'
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource

volumes:
  es:
  ch:
  grafana:
