version: '3.1'

services:

  wordpress:
    image: wordpress:php7.4
    restart: always
    ports:
      - 8081:80
    env_file:
      - .wp-env
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WP_ENVIRONMENT_TYPE: ${WP_ENVIRONMENT_TYPE:-local}
      ALTIS_ACCELERATE_PINPOINT_ENDPOINT: http://localhost:3399
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WORDPRESS_DEBUG_LOG', true );
        define( 'WORDPRESS_DEBUG_DISPLAY', true );
    volumes:
      - ./:/var/www/html/wp-content/plugins/altis-accelerate
      - ./.wordpress:/var/www/html

  db:
    image: mariadb
    restart: always
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
